import { DatabaseManager } from './DatabaseManager.js';
import { randomUUID } from 'crypto';

// ── Types ─────────────────────────────────────────────────────────────────────

export type MemoryScope    = 'workspace' | 'copilot-sayon' | 'copilot-seren' | 'global';
export type MemoryCategory = 'decision' | 'code_pattern' | 'preference' | 'project_context' | 'session_fact';

export interface MemoryRecord {
  id?:          string;   // generated by insert() if not provided
  content:      string;
  scope:        MemoryScope;
  category:     MemoryCategory;
  entity?:      string;   // file path, persona name, project name, or null
  threadId?:    string;
  sourceMsgId?: string;
}

export interface MemorySearchResult {
  id:         string;
  content:    string;
  category:   MemoryCategory;
  scope:      MemoryScope;
  score:      number;
  created_at: string;
}

// Embedding dimension for nomic-embed-text-v1.5
const EMBED_DIM = 768;

// ── Store ─────────────────────────────────────────────────────────────────────

export class MemoryStore {
  constructor(private db: DatabaseManager) {}

  /**
   * Called once at DB init.
   * Loads the vss extension and creates the memory_embeddings table + HNSW index.
   * If vss is not available (e.g. older DuckDB build without the extension),
   * logs a warning and continues — the rest of PHOBOS still works, RAG is silently disabled.
   */
  async ensureTable(): Promise<void> {
    try {
      // Belt-and-suspenders: if the DatabaseManager config didn't set the extension
      // directory (e.g. in test scripts that create their own DB instance), set it
      // now via SQL before attempting LOAD vss.
      const { BUNDLED_EXTENSION_DIR } = await import('./DatabaseManager.js');
      if (BUNDLED_EXTENSION_DIR) {
        // Escape backslashes for Windows paths in SQL
        const escaped = BUNDLED_EXTENSION_DIR.replace(/\\/g, '/');
        await this.db.run(`SET extension_directory='${escaped}'`);
      }
      await this.db.run(`LOAD vss`);
    } catch (err) {
      console.warn('[MemoryStore] DuckDB vss extension not available — semantic memory disabled:', (err as Error).message);
      return;
    }

    await this.db.run(`
      CREATE TABLE IF NOT EXISTS memory_embeddings (
        id            VARCHAR PRIMARY KEY,
        content       TEXT        NOT NULL,
        embedding     FLOAT[${EMBED_DIM}] NOT NULL,
        scope         VARCHAR     NOT NULL,
        category      VARCHAR     NOT NULL,
        entity        VARCHAR,
        thread_id     VARCHAR,
        source_msg_id VARCHAR,
        created_at    TIMESTAMP   DEFAULT now()
      )
    `);

    // HNSW index over the embedding column — cosine similarity.
    // CREATE INDEX IF NOT EXISTS is not supported for HNSW in all DuckDB builds;
    // catch and ignore if the index already exists.
    try {
      await this.db.run(`
        CREATE INDEX memory_hnsw
          ON memory_embeddings USING HNSW (embedding)
          WITH (metric = 'cosine')
      `);
    } catch {
      // Index already exists — normal on subsequent startups.
    }

    await this.db.run(`
      CREATE INDEX IF NOT EXISTS idx_memory_scope_cat
        ON memory_embeddings(scope, category)
    `);

    console.log('[MemoryStore] Semantic memory table ready');
  }

  /**
   * Insert a memory record with a pre-computed embedding vector.
   * The embedding must be EMBED_DIM (768) floats — callers obtain it from EmbedClient.
   */
  async insert(record: MemoryRecord, embedding: number[]): Promise<string> {
    const id  = randomUUID();
    const vec = `[${embedding.join(',')}]`;

    await this.db.run(`
      INSERT INTO memory_embeddings
        (id, content, embedding, scope, category, entity, thread_id, source_msg_id)
      VALUES (?, ?, ${vec}::FLOAT[${EMBED_DIM}], ?, ?, ?, ?, ?)
    `, [
      id,
      record.content,
      record.scope,
      record.category,
      record.entity    ?? null,
      record.threadId  ?? null,
      record.sourceMsgId ?? null,
    ]);

    return id;
  }

  /**
   * Cosine-similarity search filtered to a single scope + optional category.
   * Returns top-k results ordered by score descending.
   */
  async search(
    queryVec: number[],
    scope: MemoryScope,
    category: MemoryCategory | null,
    k: number,
  ): Promise<MemorySearchResult[]> {
    const vec = `[${queryVec.join(',')}]`;

    const sql = category
      ? `SELECT id, content, category, scope, created_at,
               array_cosine_similarity(embedding, ${vec}::FLOAT[${EMBED_DIM}]) AS score
           FROM memory_embeddings
          WHERE scope = ? AND category = ?
          ORDER BY score DESC
          LIMIT ?`
      : `SELECT id, content, category, scope, created_at,
               array_cosine_similarity(embedding, ${vec}::FLOAT[${EMBED_DIM}]) AS score
           FROM memory_embeddings
          WHERE scope = ?
          ORDER BY score DESC
          LIMIT ?`;

    const params = category ? [scope, category, k] : [scope, k];

    return this.db.query<MemorySearchResult>(sql, params);
  }

  /**
   * Search across multiple scopes simultaneously.
   * Results are merged and re-sorted by score, returning top-k overall.
   */
  async searchMultiScope(
    queryVec: number[],
    scopes: MemoryScope[],
    k: number,
  ): Promise<MemorySearchResult[]> {
    if (scopes.length === 0) return [];
    const vec       = `[${queryVec.join(',')}]`;
    const placeholders = scopes.map(() => '?').join(', ');

    const sql = `
      SELECT id, content, category, scope, created_at,
             array_cosine_similarity(embedding, ${vec}::FLOAT[${EMBED_DIM}]) AS score
        FROM memory_embeddings
       WHERE scope IN (${placeholders})
       ORDER BY score DESC
       LIMIT ?`;

    return this.db.query<MemorySearchResult>(sql, [...scopes, k]);
  }

  /** Delete all embeddings tied to a thread (e.g. on thread deletion). */
  async deleteByThread(threadId: string): Promise<void> {
    await this.db.run(`DELETE FROM memory_embeddings WHERE thread_id = ?`, [threadId]);
  }
}
